title: John Paul Mbuthia # your name (or website title) here
logo: "/images/logo.jpg?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  A spatial data analyst student with a passion in spatial data science, who is interested in data visualization and analytics to create compelling stories.
  <br><br>
  Currently looking for an attachment. 
  <br><br>
  <a href="https://www.linkedin.com/in/john-paul-gitata-1861bb1b9/">View My LinkedIn Profile</a> 
  <br><br>
  <a href="https://drive.google.com/file/d/1lOOIZL0Mvqj3od6Jfmdj7CP7ZyvxixFQ/view">Resume</a>
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
